version: "3"
services: 
  grafana:
    image: "grafana/grafana:6.0.1"
    container_name: "grafana"
    ports: 
      - "3000:3000"
    environment: 
      - "GF_SERVER_ROOT_URL="
      - "GF_SECURITY_ADMIN_PASSWORD="
      #- "GF_INSTALL_PLUGINS="
    restart: "always"
    volumes: 
      - "grafana-data:/var/lib/grafana"
      - "grafana-etc:/etc/grafana/"
      - "grafana-logs:/var/log/grafana"
      - "grafana-home:/usr/share/grafana"

volumes: 
  grafana-data:
  grafana-etc:
  grafana-logs:
  grafana-home:
