version: "3"
services: 
  mysql:
    image: "mysql:5.6"
    container_name: "mysql"
    restart: "always"
    environment: 
      - "MYSQL_ROOT_PASSWORD="
    ports: 
      - "3306:3306"
    volumes: 
      - "mysql-data:/var/lib/mysql"
      - "mysql-etc:/etc/mysql/conf.d"

  adminer:
    image: "adminer:4.7.1"
    container_name: "adminer"
    restart: "always"
    ports: 
      - "8080:8080"
      - "9000:9000"
    
  
volumes: 
  mysql-data:
  mysql-etc: