---

- name: install docker prepare
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - python2-pip

- firewalld:
    rich_rule: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 'rule family=ipv4 source address="{{ jms_network }}" port protocol=tcp port="{{ guacamole_http_port }}" accept'
  when:
    - enable_firewalld|default(false)

- name: add docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/7/$basearch/stable
    gpgcheck: no
    enabled: 1
  notify: yum-clean-metadata

- name: install docker-ce
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce

- name: create docker directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/docker

- name: copy docker mirrors file
  copy:
    src: "{{ downloads_dir }}/{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: daemon.json, dest: /etc/docker/daemon.json }
  notify:
    - restart docker

- meta: flush_handlers

- name: enable docker automatic start
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - docker

- pip:
    name: "{{ item }}"
    extra_args: -i {{ pip_mirrors }}
  loop:
    - docker-py

- name: create guacamole container
  docker_container:
    name: jms_guacamole
    image: "jumpserver/jms_guacamole:{{ jms_version }}"
    state: started
    ports:
      - "8081:8080"
    env:
      JUMPSERVER_KEY_DIR: "/config/guacamole/key"
      JUMPSERVER_SERVER: "http://{{ nginx_server }}"
      BOOTSTRAP_TOKEN: "{{ bootstrap_token }}"
