version: "3"
services: 
  zfile:
    build: "."
    container_name: "zfile"
    restart: "always"
    volumes: 
      - "/etc/localtime:/etc/localtime"
      - "./db:/root/.zfile-new/db/"
    ports: 
      - "8080:8080"