version: "3"
services:
  kong:
    image: "kong:0.11.2"
    container_name: "kong"
    depends_on:
      - "kong-postgres"
      - "kong-migrations"
    restart: "always"
    environment:
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
      - "KONG_CASSANDRA_CONTACT_POINTS=db"
      - "KONG_PG_DATABASE=kong"
      - "KONG_PG_HOST=kong-postgres"
      - "KONG_DATABASE=postgres"
      - "KONG_PG_PASSWORD=yourpassword"
      - "KONG_PG_USER=kong"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
    networks:
      - "kong-net"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

  kong-postgres:
    image: "postgres:9.6"
    container_name: "kong-postgres"
    restart: "always"
    environment:
      - "POSTGRES_PASSWORD=yourpassword"
      - "POSTGRES_USER=kong"
      - "POSTGRES_DB=kong"
    networks:
      - "kong-net"
    ports:
      - "5432:5432"
    volumes:
      - "kong-data:/var/lib/postgresql/data"

  kong-migrations:
    image: "kong:0.11.2"
    command: "kong migrations up"
    depends_on:
      - "kong-postgres"
    environment:
      - "KONG_DATABASE=postgres"
      - "KONG_PG_DATABASE=kong"
      - "KONG_PG_HOST=kong-postgres"
      - "KONG_PG_PASSWORD=yourpassword"
      - "KONG_PG_USER=kong"
    links:
      - "kong-postgres:kong-postgres"
    networks:
      - "kong-net"
    restart: "on-failure"

  kong-dashboard:
    image: "pgbi/kong-dashboard:v3.5.0"
    container_name: "kong-dashboard"
    restart: "always"
    depends_on: 
      - "kong-postgres"
      - "kong-migrations"
      - "kong"
    ports: 
      - "8084:8080"
    command: start --kong-url http://kong:8001 --basic-auth bboysoul=yourpassword
    networks:
      - "kong-net"

networks:
  kong-net:

volumes:
  kong-data: