---
- name: Erlang安装
  hosts: all
  user: root
  gather_facts: true
  tags: erlang
  vars_files:
    - etc/ansible/playbooks/var.yaml
  tasks:
    - name: 创建Openssl解压目录
      file: path={{ Openssl_tar_xf_dir }} state=directory owner={{ user }} group={{ group }}
    - name: 创建Otp解压目录
      file: path={{ Otp_tar_xf_dir }} state=directory owner={{ user }} group={{ group }}

    - name: 解压openssl文件至目标主机
      unarchive: src={{ Openssl_file }}/{{ Openssl_packName }} dest={{ Openssl_tar_xf_dir }}
    - name: 解压otp文件至目标主机
      unarchive: src={{ Openssl_file }}/{{ Otp_packName }} dest={{ Otp_tar_xf_dir }}
    ### Openssl ###
    - name: make_clean
      shell: make clean chdir={{ Openssl_tar_xf_dir }}/openssl-{{ Openssl_version }}/

    - name: config_openssl_ERLANG环境
      shell: ./config --prefix=/usr/local/ssl chdir={{ Openssl_tar_xf_dir }}/openssl-{{ Openssl_version }}/

    - name: 变更openssl的Makefile
      shell: sed -i 's/DGHASH_ASM/DGHASH_ASM -fPIC/' Makefile  chdir={{ Openssl_tar_xf_dir }}/openssl-{{ Openssl_version }}/

    - name: make_openssl_ERLANG环境
      shell: make chdir={{ Openssl_tar_xf_dir }}/openssl-{{ Openssl_version }}/

    - name: make_install_openssl_ERLANG环境
      shell: make install chdir={{ Openssl_tar_xf_dir }}/openssl-{{ Openssl_version }}/

    ### Otp ###
    - name: 配置Otp
      shell: CHOST="x86_64-pc-linux-gnu" CFLAGS="-march=nocona -O2 -pipe" CXXFLAGS="-march=nocona -O2 -pipe" chdir={{ Otp_tar_xf_dir }}/otp_src_{{ Otp_version }}/

    - name: config_otp
      shell: ./configure --enable-kernel-poll \
        --prefix={{ Otp_data_dir }}
        --enable-threads     \
        --enable-smp-support \
        --enable-hipe        \
        --with-ssl=/usr/local/ssl/ \
        chdir={{ Otp_tar_xf_dir }}/otp_src_{{ Otp_version }}/

    - name: make_otp
      shell: make -j  {{ ansible_processor_vcpus }} chdir={{ Otp_tar_xf_dir }}/otp_src_{{ Otp_version }}/

    - name: make_install_otp
      shell: make install -j  {{ ansible_processor_vcpus }} chdir={{ Otp_tar_xf_dir }}/otp_src_{{ Otp_version }}/

    - name: 配置软链接
      shell: ln -s {{ Otp_data_dir }}/bin/* /usr/bin/

    - name: 变更php.ini配置
      shell:
        sed -i '736 i extension_dir = "/data/php/lib/php/extensions/no-debug-non-zts-20151012"' /data/php/etc/php.ini && \
        sed -i 's/;date.timezone =/date.timezone = PRC/' /data/php/etc/php.ini && \
        sed -i 's/short_open_tag = Off/short_open_tag = On/' /data/php/etc/php.ini
