version: "3"
services: 
  nexus:
    image: "sonatype/nexus3:3.15.2"
    container_name: "nexus"
    restart: "always"
    ports: 
      - "8081:8081"
    volumes: 
      - "nexus-data:/nexus-data"
      - "nexus:/opt/sonatype/nexus"
    #environment: 
    #  - "INSTALL4J_ADD_VM_PARAMS"

volumes: 
  nexus-data:
  nexus: