version: "3"
services: 
  redis:
    image: "redis:4.0"
    container_name: "redis"
    restart: "always"
    volumes: 
      - "redis-data:/var/lib/redis"
    ports: 
      - "6379:6379"

volumes: 
  redis-data: