version: "3"
services: 
  netdata:
    image: "netdata/netdata:v1.16.0-amd64"
    container_name: "netdata"
    restart: "always"
    volumes: 
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "apparmor=unconfined"
    ports: 
      - "19999:19999"

