version: "3"
services: 
  mariadb:
    image: "mariadb:10.3.14"
    container_name: "mariadb"
    restart: "always"
    environment: 
      - "MYSQL_ROOT_PASSWORD="
    ports: 
      - "3306:3306"
    volumes: 
      - "mariadb-data:/var/lib/mysql"
      - "mariadb-etc:/etc/mysql/conf.d"
      - "/etc/localtime:/etc/localtime"


  # adminer:
  #   image: "adminer:4.7.1"
  #   container_name: "adminer"
  #   restart: "always"
  #   ports: 
  #     - "8080:8080"
  #     - "9000:9000"
    
  
volumes: 
  mariadb-data:
  mariadb-etc: