---

- firewalld:
    zone: public
    port: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - "{{ http_port }}/tcp"
    - "{{ ssh_port }}/tcp"
  when:
    - enable_firewalld|default(false)

- firewalld:
    zone: public
    port: "{{ https_port }}/tcp"
    permanent: yes
    immediate: yes
    state: enabled
  when:
    - https_port is defined
    - enable_firewalld|default(false)

- shell: setenforce 0
  when:
    - enable_selinux|default(false)

- name: Disable SELinux
  selinux:
    state: disabled

- name: install nfs-utils
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-utils

- name: create nfs data directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ nfs_dest_dir }}"

- name: mount nfs data directory
  mount:
    fstype: nfs
    opts: rw
    src: "{{ nfs_server }}:{{ nfs_src_dir }}"
    path: "{{ nfs_dest_dir }}"
    state: mounted

- name: copy file to nginx
  copy:
    src: "{{ item }}"
    dest: "{{ install_dir }}/"
  loop:
    - "{{ downloads_dir }}/luna.tar.gz"
    - "{{ downloads_dir }}/{{ tengine_name }}"
  notify:
    - extract luna

- name: install tengine-server
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ install_dir }}/{{ tengine_name }}"

- name: remove nginx default conf
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/conf.d/default.conf

- name: copy nginx conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'nginx.conf.j2', dest: '/etc/nginx/nginx.conf' }
    - { src: 'jumpserver.conf.j2', dest: '/etc/nginx/conf.d/jumpserver.conf' }
  notify:
    - restart nginx

- name: enable nginx automatic start
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - nginx
