---
- name: MySQL安装
  hosts: all
  user: root
  tags: mysql
  gather_facts: true
  vars_files:
    - /etc/ansible/playbooks/var.yaml
  tasks:
    - name: 创建MySQL组
      group: name={{ MySQL_group }}

    - name: 创建MySQL用户
      user: name={{ MySQL_user }} group={{ MySQL_group }}
    - yum: name="autoconf,bzip2,bzip2-devel,cmake,curl,curl-devel,e2fsprogs,e2fsprogs-devel,freetype,freetype-devel,gcc,gcc-c++,git,glibc,glibc-devel,gmp,gmp-devel,krb5-devel,libcurl,libcurl-devel,libidn,libidn-devel,libjpeg,libjpeg-devel,libmcrypt,libmcrypt-devel,libpng,libpng-devel,libtool-ltdl-devel,libxml2,libxml2-devel,libxslt,libxslt-devel,lrzsz,mysql-devel,ncurses,ncurses-devel,ntp,openldap,openldap-clients,openldap-devel,openldap-servers,openssl,openssl-devel,perl-CPAN,readline,readline-devel,screen,svn,unixODBC,unixODBC-devel,unzip"

#    - name: 创建日志目录
#      file: path={{ log_dir }} state=directory owner={{ MySQL_user }} group={{ MySQL_group }}
    - name: 创建MySQL数据目录
      file: path={{ MySQL_data_dir }} state=directory owner={{ MySQL_user }} group={{ MySQL_group }}
    - name: 创建MySQL存放密码目录
      file: path={{ save_dir }} state=directory 
    - name: 创建MySQL解压目录
      file: path={{ MySQL_tar_xf_dir }} state=directory owner={{ MySQL_user }} group={{ MySQL_group }}
    - name: 创建MySQL-binlog目录
      file: path={{ MySQL_binlog_dir }} state=directory owner={{ MySQL_user }} group={{ MySQL_group }}
    - name: 创建MySQL-relaylog目录
      file: path={{ MySQL_relaylog_dir }} state=directory owner={{ MySQL_user }} group={{ MySQL_group }}
    - name: 创建MySQL-sock目录
      file: path={{ MySQL_sock_dir }} state=directory owner={{ MySQL_user }} group={{ MySQL_group }}
    #    - name: create_dir
    #      file: path={{ MySQL_shell_dir }} state=directory owner={{ user }} group={{ group }}

    - name: 解压MySQL至目标主机
      unarchive: src={{ MySQL_pack }}/{{ MySQL_packName }} dest={{ MySQL_tar_xf_dir }}

    - name: cmake
      command: cmake . -DCMAKE_INSTALL_PREFIX={{ MySQL_data_dir }} \
        -DWITH_BOOST=boost \
        -DSYSCONFDIR=/etc \
        -DWITH_INNOBASE_STORAGE_ENGINE=1 \
        -DWITH_PARTITION_STORAGE_ENGINE=1  \
        -DWITH_FEDERATED_STORAGE_ENGINE=1 \
        -DWITH_BLACKHOLE_STORAGE_ENGINE=1 \
        -DWITH_MYISAM_STORAGE_ENGINE=1 \
        -DENABLED_LOCAL_INFILE=1 \
        -DENABLE_DTRACE=0 \
        -DDEFAULT_CHARSET=utf8mb4 \
        -DDEFAULT_COLLATION=utf8mb4_general_ci \
        -DWITH_EMBEDDED_SERVER=1 \
        chdir={{ MySQL_tar_xf_dir }}/mysql-{{ MySQL_version }}/

    - name: make
      command: make  chdir={{ MySQL_tar_xf_dir }}/mysql-{{ MySQL_version }}/
    - name: make_install
      command: make install chdir={{ MySQL_tar_xf_dir }}/mysql-{{ MySQL_version }}/

    - name: 创建MySQL命令软链接
      shell: ln -sf {{ MySQL_data_dir }}/bin/* /usr/bin/

    - name: 复制MySQL的my.cnf至目标主机
      copy: src={{ MySQL_pack }}/my.cnf dest={{ MySQL_data_dir }}/3306/my.cnf backup=yes force=yes

    - name: MySQL初始化
      shell: mysqld --defaults-file={{ MySQL_data_dir }}/3306/my.cnf --initialize-insecure --basedir={{ MySQL_data_dir }} --datadir={{ MySQL_data_dir }}/3306/data --user={{ MySQL_user }}

    - name: 复制mysql.sh(启动脚本)至目标主机
      copy: src={{ MySQL_pack }}/mysql.sh dest={{ MySQL_data_dir }}/3306/mysql  backup=yes

    - name: 变更MySQL(启动脚本)权限
      shell: chmod +x {{ MySQL_data_dir }}/3306/mysql
    - name: 变更MySQL数据目录权限
      shell: chmod +w {{ MySQL_data_dir }}
    - name: 变更MySQL数据目录属组属主
      shell: chown -R mysql:mysql {{ MySQL_data_dir }}

    - name: 启动MySQL
      shell: /data/mysql/3306/mysql start

    - name: 创建MySQL-sock软链接
      shell: ln -sf /tmp/mysql.sock /var/lib/mysql/mysql.sock

    - name: 创建MySQL启动脚本
      shell: echo "/data/mysql/3306/mysql start" > /root/mysql_start
    - name: 创建MySQL停止脚本
      shell: echo "/data/mysql/3306/mysql stop" > /root/mysql_stop
    - name: 设置MySQL开机自启
      shell: echo "/root/mysql_start" >> /etc/rc.local
    - name: 变更MySQL启动停止脚本权限
      shell: chmod 700 /root/mysql*

    - name: 获取MySQL-root用户密码保存至存放密码目录
      shell: </dev/urandom tr -dc 0-9-A-Z-a-z|head -c ${1:-16} > {{ save_dir }}/mysql_root
    - name: 获取MySQL-普通用户密码保存至存放密码目录
      shell: </dev/urandom tr -dc 0-9-A-Z-a-z|head -c ${1:-16} > {{ save_dir }}/mysql_user

    - name: 变更MySQL-sock目录属组属主
      shell: chown -R mysql:mysql {{ MySQL_sock_dir }}
    - name: 变更MySQL数据目录属组属主
      shell: chown -R mysql:mysql {{ MySQL_data_dir }}
    - name: 变更存放密码目录权限
      shell: chmod -R 700 {{ save_dir }}

    - name: 修改MySQL-root密码
      shell: /bin/mysqladmin -u root password $(cat /data/save/mysql_root)
    ### admin ###
    - name: 设置admin用户localhost登录
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' IDENTIFIED BY '37eJZR8RGZTd42l5l3hrUBqi';"
    - name: 创建admin用户127.0.0.1登录
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"GRANT ALL PRIVILEGES ON *.* TO 'admin'@'127.0.0.1' IDENTIFIED BY '37eJZR8RGZTd42l5l3hrUBqi';"
    ### root ###
    - name: 设置root用户localhost登录
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '$(cat /data/save/mysql_root)';"
    - name: 创建root用户127.0.0.1登录
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"GRANT ALL PRIVILEGES ON *.* TO 'root'@'127.0.0.1' IDENTIFIED BY '$(cat /data/save/mysql_root)';"
    ### 添加用户
    - name: 创建用户xge
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"grant all privileges on *.* to 'xge'@'%' identified by '$(cat /data/save/mysql_root)';"
    - name: 移除用户xge部分权限
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"REVOKE EXECUTE, PROCESS, SHOW DATABASES, CREATE USER, FILE, GRANT OPTION, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER, CREATE ROUTINE, ALTER ROUTINE ON *.* FROM 'xge'@'%';"
    ## Create DB
    - name: 创建库
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"create database {{ MySQL_DB }};"
    - name: 创建用户
      shell: /usr/bin/mysql -u root -p$(cat /data/save/mysql_root) -e"grant all privileges on {{ MySQL_DB }}.* to '{{ MySQL_DBUser }}'@'{{ MySQL_DBhosts }}'  IDENTIFIED BY '$(cat /data/save/mysql_user)';"

    ### 将MySQL数据库的动态链接库共享至系统链接 ###
    - name: 停止MySQL
      shell: /data/mysql/3306/mysql stop

    - name: 将MySQL数据库的动态链接库共享至系统链接
      shell: echo "/data/mysql/lib" > /etc/ld.so.conf.d/mysql.conf

    - name: 启动MySQL
      shell: /data/mysql/3306/mysql start
